<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * This environment connect to the LIVE calculator API
     */
    const PRODUCTION = "production";
}
